spring:
  config:
    activate:
      on-profile: deploy

login:
  keys:
    cipher: parkyoonhosecret
    jwt: thisistestusersecretkeyprojectnameisnexterspimooooooooooo
    clientId: 9991a02c1253223dd0fa649fab9e0df9
  apis:
    kauth: https://kauth.kakao.com
    kapi: https://kapi.kakao.com
    apple: https://appleid.apple.com

auth:
  url: http://localhost:8080
  conn:
    connect-timeout: 3000
    read-timeout: 2000
    user-agent: PIMO

springdoc:
  default-consumes-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html